### ISSUE TITLE
Strain Token Support

### ISSUE THREAD

**Issue by brianjpugh** [npiegdon/xwing2-quick-reference#1]
Please add the strain token:

STRAIN￼
A ship is strained while it has at least one strain token. While a strained
ship defends, it rolls 1 fewer defense die. The strain token is a red token.
• After a strained ship defends, it removes 1 strain token.
• After a strained ship executes a blue maneuver, it removes 1 strain
token..

**Comment by npiegdon** [comment]
Thanks!  I missed a few of the new things in Wave 4 & 5.  The next update will include Dock/Undock/Emergency Undock and couple other small details.
