### ISSUE TITLE
Suggestion on ROAD placement

### ISSUE THREAD

**Issue by starjoe4** [npiegdon/xwing2-quick-reference#13]
This is a great reference!  Regarding ROAD, one suggestion, you could move that text before (above) the System Phase text and make it explicit that the timing is prior to setting dials (after setup) and prior to putting out objectives or obstacles (before setup).

**Comment by gabindu** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/12254984/184389590-7b19fcd6-53ae-4d37-8ea9-c9e8f438a9fd.png)
