### ISSUE TITLE
Adobe CS6 Compatible

### ISSUE THREAD

**Issue by GerritK** [npiegdon/xwing2-quick-reference#2]
Is it possible to save the .ai as CS6 compatible? I would add a german version.

**Comment by npiegdon** [comment]
With any luck it should be CS6 compatible now.

**Comment by npiegdon** [comment]
Uh oh, it looks like saving it as compatible with CS6 broke the type layers with the dice icons.  (My guess is that CS6 didn't have support for full-color fonts.)

I'm going to have to roll this back for the next release, sorry!
