### ISSUE TITLE
Jam action should include bullseye range 1-2

### ISSUE THREAD

**Issue by brobzilla** [npiegdon/xwing2-quick-reference#3]
According to the rules ref

> 2. Choose an enemy ship at range 1, or at range 1–2 in the jamming ship's bullseye

I would update myself but don't have the tools to do it easily.  Thanks!

**Comment by npiegdon** [comment]
Thanks for the issue!  I hadn't been following rules changes for about a year, so I missed this one.  It's fixed in v5.
