### ISSUE TITLE
Update to latest AMG rulings

### ISSUE THREAD

**Issue by NINE78** [npiegdon/xwing2-quick-reference#8]
Would it be possible to update to latest AMG rulings? E.g. not using force to adjust attack dice at range 0?

Thank you!! This quick reference is really helpful.

**Comment by gabindu** [comment]
I just made all the changes in the latest commit. Can you please proof-read the pdf-file and let us know if you notice any mistakes or omissions, before I declare this the official new release? Thanks!

**Comment by NINE78** [comment]
Thanks for the *very* prompt turnaround. It's looking great!

As suggestions:
Perhaps add sideslip maneuver notes?

The obstacles may need some clarification:
- moving through a blaze, add skip perform action
- ending a maneuver overlapping an obstacle: skip perform action
- while at range 0 of obstacle: asteroid/debris/gas -> no attacks; chaff/gas -> no to/from locks

Thanks again!!

**Comment by gabindu** [comment]
Thanks for the feedback, I'll get on that tomorrow!

**Comment by gabindu** [comment]
I think I've now covered all this in the latest commit (b0b5a95255131cd15678c88335b39b2c4b6857b5). Can you please double-check and let me know if anything else is missing? Thanks!
